custom:
  client:
    clientId: crazy_frog
    clientSecret: 4E78AB46-5188-421A-AB1A-3827CA785538
    accessTokenUri: http://localhost:8080/server/oauth/token
    userAuthorizationUri: http://localhost:8080/server/oauth/authorize
  resource:
    userInfoUri: http://localhost:8080/server/api/me
